[package]
name = "edge"
version = "0.1.0"
authors = ["NoÃ«l Widmer <noel.widmer@gmail.com>"]
edition = "2018"

[dependencies]
domain = { path = "../domain" }
use_cases = { path = "../use_cases" }
app = { path = "../app" }
infra = { path = "../infra" }
